### ISSUE TITLE
its giving this error sir 

### ISSUE THREAD

**Issue by sparrowbb007** [FuckingToasters/discord-phone-verifier#10]
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Desktop\discord-phone-verifier-main\new version\main.py", line 100, in verify
    checktoken()
  File "C:\Users\Desktop\discord-phone-verifier-main\new version\main.py", line 93, in checktoken
    if response.json()["message"] == "401: Unauthorized":
  File "C:\Python310\lib\site-packages\httpx\_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

i checked if the token it was working

**Comment by FuckingToasters** [comment]
`pip install brotlipy`

description: the username contain special characters like emojis
