### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by seawolph** [FuckingToasters/discord-phone-verifier#22]
Thanks so much for making this by the way man, sincerely.

Could you help me with this error?

Exception in thread Thread-1 (verify):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\Desktop\new version\main.py", line 52, in verify
    TOKENCOMBO, TOKEN, PASSWORD = gettoken()
  File "C:\Users\Administrator\Desktop\new version\main.py", line 50, in gettoken
    TOKEN, PASSWORD = TOKENCOMBO.split(":")
ValueError: too many values to unpack (expected 2)

**Comment by FuckingToasters** [comment]
The tool is looking inside tokens.txt for a token and a password seperated by ":" it needs an password to confirm the phone number adding (you'll need to provide an password when doing manually too) so what this means, is that you need to put token:password in tokens.txt and not for example item1:item2:item3 befusee it is trying to extract the 2 values in 2 variables but this won't work when it finds 3 values.


If you want to format your tokens correctly, I made a tool for that too: https://github.com/FuckingToasters/discord-token-checker

**Comment by FuckingToasters** [comment]
closing due to inactivity.
