### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Valemy** [FuckingToasters/discord-phone-verifier#7]
yo bro why get these errors so much 
![image](https://user-images.githubusercontent.com/114499883/196246689-4645e7d4-d6c9-4724-9f9d-f78e0bae0275.png)

**Comment by FuckingToasters** [comment]
> yo bro why get these errors so much ![image](https://user-images.githubusercontent.com/114499883/196246689-4645e7d4-d6c9-4724-9f9d-f78e0bae0275.png)

This don't show me anything rly, please send me the full error in text so i can help you.....

**Comment by Valemy** [comment]
Exception in thread Thread-17 (verify):
Traceback (most recent call last):
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 218, in handle_request
    resp = self._pool.handle_request(req)
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection_pool.py", line 253, in handle_request
    raise exc
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\connection_pool.py", line 237, in handle_request
    response = connection.handle_request(request)
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\http_proxy.py", line 313, in handle_request
    return self._connection.handle_request(request)
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\http11.py", line 105, in handle_request
    raise exc
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\http11.py", line 84, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\http11.py", line 148, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpcore\_sync\http11.py", line 191, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\theca\OneDrive\Bureau\new version\main.py", line 199, in verify
    VERIFYCODE = waitsms()
  File "C:\Users\theca\OneDrive\Bureau\new version\main.py", line 194, in waitsms
    verify(totalthreads, threadindex, proxytype)
  File "C:\Users\theca\OneDrive\Bureau\new version\main.py", line 199, in verify
    VERIFYCODE = waitsms()
  File "C:\Users\theca\OneDrive\Bureau\new version\main.py", line 194, in waitsms
    verify(totalthreads, threadindex, proxytype)
  File "C:\Users\theca\OneDrive\Bureau\new version\main.py", line 101, in verify
    checktoken()
  File "C:\Users\theca\OneDrive\Bureau\new version\main.py", line 91, in checktoken
    response = client.get("https://discord.com/api/v9/users/@me")
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1039, in get
    return self.request(
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 815, in request    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 902, in send
    response = self._send_handling_auth(
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 930, in _send_handling_auth
    response = self._send_handling_redirects(
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 967, in _send_handling_redirects
    response = self._send_single_request(request)
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_client.py", line 1003, in _send_single_request
    response = transport.handle_request(request)
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 217, in handle_request
    with map_httpcore_exceptions():
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\theca\AppData\Local\Programs\Python\Python310\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

**Comment by FuckingToasters** [comment]
> httpx.RemoteProtocolError: Server disconnected without sending a response.

`httpx.RemoteProtocolError: Server disconnected without sending a response.` seems like a connection error, if you use proxies then the proxies might've been the problem.
